# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

devise_secret_key: devise_secret_key
devise_sender: 'no-reply@example.com'
buy_now_url_template: "http://buy-this-product.com/buy?product=%s"
warranty_registration_url: http://foo.bar.com
warranty_repair_url: http://repair.foo.com
dealer_portal_url: http://portal.foo.com
service_center_registration_recipient: 'service@foo.com'
brands_api_host: api-server.com
cheetahmail_aid: "1234567"
cheetahmail_sub: "98765432"
cheetahmail_username: cheetah-user
cheetahmail_password: cheetah-pass
show_placeholders: "true"

production:
  harmanpro_database_password: database_password
  secret_key_base: secret_key_base
  cheetahmail_aid: "1234567"
  cheetahmail_sub: "98765432"
  cheetahmail_username: cheetah-user
  cheetahmail_password: cheetah-pass
  show_placeholders: "false"
  exception_recipients: "you@something.com, someoneelse@them.com"

